### PR TITLE
Fix handling of patterns that are method names

### LINKED ISSUE #3679: Using a route of name 'watch' blows up in Firefox
## Version
2.6.0

## Test Case
http://jsbin.com/yibililodo/edit?html,js,output

## Steps to reproduce
Firefox >45
Have a nested path of 'watch' or 'unwatch'
Use router.push() to navigate to them.

## Expected Behavior
Routes to the watch route.

## Actual Behavior
Blows up.

Firefox apparently has a `watch` and `unwatch` function on every object.  Because of this, when `PatternUtils.compilePattern()` is hit when pattern = 'watch' it returns the watch function.  Then when trying to call `paramNames.some()` in computeChangesRoutes.js it blows up since `some()` can't be called on a function.

### PR DESCRIPTION
**Pull request by taion**
Fixes #3679.

Includes #3678 (needed for CI to pass).

`PatternUtils` is sort of a mess, incidentally. There's no reason to export `compilePattern`, and there's no real reason that `getParams` should still exist (nothing calls it). I also don't know why `getRouteParams` is completely separate module, either.

I want to fix/deprecate, but it's not that compelling right now.

### CODE REVIEW

File: modules/__tests__/matchPattern-test.js [hunk 1]
```diff
@@ -41,4 +41,8 @@ describe('matchPattern', function () {
     assertMatch('/**/*.jpg', '/files/path/to/file.jpg', '', [ 'splat', 'splat' ], [ 'files/path/to', 'file' ])
   })
 
+  it('works with patterns that match built-in names', function () {
```
Comment (taion) [inline modules/__tests__/matchPattern-test.js]: This test case passes against `master`, but worth asserting here anyway.

**Comment by taion** [comment]
Rebased

File: modules/__tests__/matchPattern-test.js (hunk 1 above)
Comment (timdorr) [inline modules/__tests__/matchPattern-test.js]: Can you get it to fail against Firefox with 'watch'?

Comment (taion) [inline modules/__tests__/matchPattern-test.js]: Not here – `matchPattern` prepends a `/` to all patterns to match the pathname.

The failing test case is the `getParamsName` one, which currently would fail on all browsers.
